version: '2.0.{build}'
image: Visual Studio 2019
build_script:
  - ps: dotnet restore .
  - ps: dotnet build . --no-restore --configuration Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'